### ISSUE TITLE
Zebra printing uses wrong Regular Expression for code merging

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-Checkin#4]
Rock server-side printing uses the following regular expression `(?<=\^FD){0}(?=\^FS)`.

iOS based printing uses this regular expression `(\\^FT.*\\^FD)(%@)(\\^FS)`.

While most fields DO start with `^FT`, not all. One person was trying to use `^FO`, which is perfectly valid option.

iOS app should be updated to use the same regular expression format as the other printing services.

**Comment by cabal95** [comment]
@edmistj 

I just noticed (remembered) this one. Do we want to roll this fix into the code before release too?

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/CheckIn/Success.ascx.cs#L183

vs

https://github.com/SparkDevNetwork/Rock-Checkin/blob/master/ios/RockCheckin/Classes/ZebraPrint.m#L207

**Comment by edmistj** [comment]
Not sure I remember what this was fixing.

**Comment by cabal95** [comment]
It wasn't fixing a specific bug per-se. It was to sync up the RegEx that is used in the core Success page when doing label merge field replacement and the RegEx that is used by the iPad app doing the same. They use different Regular Expressions, so a ZPL that works when doing server-side printing might not work the same when doing iPad printing (because a merge field might not get inserted because the RegEx doesn't match).

**Comment by edmistj** [comment]
Sounds like they should be the same. Could you make that change also?

**Comment by cabal95** [comment]
Yep, will do.
