### ISSUE TITLE
iPad app does not scale to fill larger displays

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock-Checkin#8]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The iPad app does not scale to fill all iPad sizes

### Steps to Reproduce

1. Get an iPad that has a larger point resolution than the standard 9.7” iPad and iPad mini
2. Install the iPad mobile check in app
3. Be a little disappointed that the app doesn’t scale to fill the whole screen
4. Put a thumbs up 👍 on this issue request

**Comment by cabal95** [comment]
@andypullen Can you post a picture of what you are seeing and also let me know exactly which iPad model you have? I don't have any iPad Pro units to test on, just the simulator.  I _think_ I'm seeing the problem, but before I go about fixing what I think is the problem, a picture of exactly what you are seeing would help.

For reference, on the iOS iPad Pro 12.9" simulator, what I see is what appears to be a small black border around the entire app. By small, I mean just a slight border. See pictures below to see the difference. If that is what you are referring to I will work on that as the fix. But if you are seeing something else I'll need to find a way to reproduce what you are seeing.

<img width="912" alt="Screen Shot 2021-03-13 at 3 00 20 PM" src="https://user-images.githubusercontent.com/1119863/111050958-f46a1900-840c-11eb-993b-5ee30a1adcaf.png">

<img width="899" alt="Screen Shot 2021-03-13 at 3 00 29 PM" src="https://user-images.githubusercontent.com/1119863/111050959-f6cc7300-840c-11eb-9ff8-b868db3ca679.png">

**Comment by andypullen** [comment]
Thanks for taking a look at this! I have an 11” iPad Pro which is where I noticed it, but someone recently donated to us a small handful of 12.9” iPads that we’re going to set up for mobile check-in.
Portrait looks ok with small borders on the top & bottom, but landscape has a larger border on the sides.

**Comment by cabal95** [comment]
@andypullen Thanks for the pictures. I _think_ this is the same issue I am seeing in the simulator so I'll work towards fixing that up. From what I read it's really just a matter of building a new version of the binary with a flag that tells iOS the app is aware of the new screen dimensions.
